name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Instalar dependencias
      run: |
        echo "Instalando dependencias (simulado)"
       

    - name: Ejecutar pruebas
      run: |
        echo "Ejecutando pruebas (simulado)"
       

    - name: Despliegue automático
      if: github.ref == 'refs/heads/main'
      run: |
        echo "Desplegando (simulado)"
       
